name: Publish Coveralls

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 22.x
      uses: actions/setup-node@v2
      with:
        node-version: 22.x
    - name: Check and create coverage file
      run: |
        npm install
        npm run test:coverage
    - name: Coveralls
      uses: coverallsapp/github-action@1.1.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
